name: 'Terraform Destroy'

on:
  workflow_dispatch

jobs:
  terraform-destroy:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve
        -var="TF_VAR_PREFIX=${{ secrets.TF_VAR_PREFIX }}"
        -var="TF_VAR_ENVIRONMENT=${{ secrets.TF_VAR_ENVIRONMENT }}"
        -var="TF_VAR_LOCATION=${{ secrets.TF_VAR_LOCATION }}"
        -var="PSQL_ADMIN_LOGIN=${{ secrets.TF_VAR_PSQL_ADMIN_LOGIN }}"
        -var="PSQL_ADMIN_PASSWORD=${{ secrets.TF_VAR_PSQL_ADMIN_PASSWORD }}" -input=false
