name: 'Terraform Destroy'

on:
  workflow_dispatch

jobs:
  terraform-destroy:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Terraform Destroy
      run: |
        TF_STRICT_MODE=false \
        terraform destroy -auto-approve \
        -var="prefix=${{ secrets.TF_VAR_PREFIX }}" \
        -var="environment=${{ secrets.TF_VAR_ENVIRONMENT }}" \
        -var="location=${{ secrets.TF_VAR_LOCATION }}" \
        -var="psql_admin_login=${{ secrets.TF_VAR_PSQL_ADMIN_LOGIN }}" \
        -var="psql_admin_password=${{ secrets.TF_VAR_PSQL_ADMIN_PASSWORD }}" -input=false \
