name: 'Terraform'

on:
  workflow_dispatch

jobs:
  terraform-destroy:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main'

      # uses: hashicorp/terraform-github-actions@master
      # with:
      #   tf_actions_version: 1.3.0
      #   tf_actions_subcommand: 'apply'
      #   tf_actions_working_dir: "./terraform"
      env:
        prefix: ${{ secrets.PREFIX }}
        environment: ${{ secrets.ENVIRONMENT }}
        location: ${{ secrets.LOCATION }}
        psql_admin_login: ${{ secrets.PSQL_ADMIN_LOGIN }}
        psql_admin_password: ${{ secrets.PSQL_ADMIN_PASSWORD }}
      run: |
        terraform apply -auto-approve -var="prefix=${{ secrets.PREFIX }}" -var="environment=${{ secrets.ENVIRONMENT }}" -var="location=${{ secrets.LOCATION }}" -var="psql_admin_login=${{ secrets.PSQL_ADMIN_LOGIN }}" -var="psql_admin_password=${{ secrets.PSQL_ADMIN_PASSWORD }}" -input=false

    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve -var="prefix=${{ secrets.PREFIX }}" -var="environment=${{ secrets.ENVIRONMENT }}" -var="location=${{ secrets.LOCATION }}" -var="psql_admin_login=${{ secrets.PSQL_ADMIN_LOGIN }}" -var="psql_admin_password=${{ secrets.PSQL_ADMIN_PASSWORD }}" -input=false
