name: 'Terraform Destroy'

on:
  workflow_dispatch

jobs:
  terraform-destroy:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.0
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.0
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"

    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.0
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"

    - name: Terraform destroy
      env:
        TF_VAR_PREFIX: ${{ secrets.TF_VAR_PREFIX }}
        TF_VAR_ENVIRONMENT: ${{ secrets.TF_VAR_ENVIRONMENT }}
        TF_VAR_LOCATION: ${{ secrets.TF_VAR_LOCATION }}
        TF_VAR_PSQL_ADMIN_LOGIN: ${{ secrets.TF_VAR_PSQL_ADMIN_LOGIN }}
        TF_VAR_PSQL_ADMIN_PASSWORD: ${{ secrets.TF_VAR_PSQL_ADMIN_PASSWORD }}
      run: |
        terraform destroy -auto-approve \
        -var="prefix=${{ secrets.TF_VAR_PREFIX }}" \
        -var="environment=${{ secrets.TF_VAR_ENVIRONMENT }}" \
        -var="location=${{ secrets.TF_VAR_LOCATION }}" \
        -var="psql_admin_login=${{ secrets.TF_VAR_PSQL_ADMIN_LOGIN }}" \
        -var="psql_admin_password=${{ secrets.TF_VAR_PSQL_ADMIN_PASSWORD }}" -input=false